# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CameraDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#     pod 'LLSimpleCamera', '~> 5.0.0'
     pod 'AFNetworking', '~> 3.1.0'
#     pod 'FCFileManager', '~> 1.0.20'

  # Pods for CameraDemo

end
